import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import { AdunitService } from '../adunit.service';
import { AdUnit } from '../components/index/AdUnit';
import {AppComponent} from "../app.component";
import { Uspass } from "../../../models/uspass";
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import {EventData} from "tns-core-modules/data/observable";
import {Button} from "tns-core-modules/ui/button";



@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.tns.html',
  styleUrls: ['./auto-generated.component.css']
})


export class AutoGeneratedComponent implements OnInit {
  ufuk: string ;
  sunal: string ;
  angForm: FormGroup;
labelText='this is amazing';
  message:string;
  returnObject:string='abc';
  params:string="";
  response: {};
  username:string;
  password:string;
  adunit:AdUnit;
   uspass: Uspass;

  onChange():void{
this.labelText='this was tapped';
}

  constructor(private app: AppComponent,
              private fb: NativeScriptFormsModule,
              private adunitservice: AdunitService,
              private data: AdunitService,)  {


  }

  isLoggingIn = true;

  toggleForm() {
    this.isLoggingIn = !this.isLoggingIn;
  }


  onButtonTap(args: EventData) {
    const button = <Button>args.object;
    console.log('login.componenete girdi:'+this.username+this.password);

    //this.uspass.auth_token='';

    let a=0;
    let uri='http://192.168.0.4:8090';
    if(a==0){
    this.adunitservice.apiChippersLogin(this.uspass,uri)
      .subscribe((uspass: Uspass) => {
        console.log('posts function çalışacak servise gidiyor');

        console.log(uspass);
        if(!uspass.islogin){
          this.message='username or password is incorrect';
        } else {
          //this.router.navigate(['logged-in']);
          this.message='fksdfjksdjflsjl';
        }

      });
    console.log('Button tapped');
  }else {
      this.response=this.adunitservice.firstLogin(this.username,this.password,this.app);
    }}
  submit() {

    console.log('login.componenete girdi:'+this.username+this.password);
    //this.response=  this.adunitservice.firstLogin(username, password,this.app);

    this.returnObject='xyz';

    if (this.isLoggingIn) {
      // Perform the login
    } else {
      // Perform the registration
    }

  }

  ngOnInit() {
    console.log("Page loaded");
    this.adunitservice.isLogin(this.app);
    this.sunal='Is login =';
    this.data.currentMessage.subscribe(message => this.message = message)
    console.log(this.message);
  }

}

