import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.css']
})
export class AutoGeneratedComponent implements OnInit {
  ufuk: string ;
  sunal: string ;

labelText='this is amazing';
  onChange():void{
this.labelText='this was tapped';
}

  constructor() { }

  ngOnInit() {

    this.sunal='sunal';
  }

}
