import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';


import { AutoGeneratedComponent} from '../app/auto-generated/auto-generated.component';
import { WelcomeComponent } from './components/welcome/welcome.component';
import { AboutComponent } from './about/about.component';
import { LoginComponent } from './components/login/login.component';
import {LoggedInComponent} from "./components/loggedIn/loggedIn.component";

export const routes: Routes = [
  {
      path: '',
      redirectTo: '/auto-generated',
      pathMatch: 'full',
  },
  {
    path: 'logged-in',
    component: LoggedInComponent,
  },
  {
    path: 'login',
    component: AutoGeneratedComponent,
  },
  {
    path: 'about',
    component: AboutComponent,
  },
  {
    path: 'auto-generated',
    component: AutoGeneratedComponent,
  },
  {
    path: 'welco',
    component: WelcomeComponent,
  },
  {
    path: 'welcome',
    component: LoggedInComponent,
  },


];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
