import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { SlimLoadingBarModule } from 'ng2-slim-loading-bar';
import {AppRoutingModule, routes} from './app-routing.module.tns';
import { AppComponent } from './app.component';
import{AutoGeneratedComponent} from './auto-generated/auto-generated.component';
import { WelcomeComponent } from './components/welcome/welcome.component';
import { AboutComponent } from './about/about.component';
import { LoginComponent } from './components/login/login.component';
import {LoggedInComponent} from "./components/loggedIn/loggedIn.component";
import { HttpClientModule } from '@angular/common/http';
import { CookieService } from 'ngx-cookie-service';
import { FormGroup,  FormBuilder,  Validators } from '@angular/forms';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {RouterModule} from "@angular/router";


// Uncomment and add to NgModule imports if you need to use two-way binding
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import {NativeScriptRouterModule} from "nativescript-angular";
import {Uspass} from "../../models/uspass";
import {MatRadioModule} from "@angular/material/radio";

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    WelcomeComponent,
    AutoGeneratedComponent,
    AboutComponent,
    LoginComponent,
    LoggedInComponent
  ],

  imports: [
    NativeScriptModule,
    HttpClientModule,
    SlimLoadingBarModule,
    NativeScriptRouterModule,
    NativeScriptFormsModule,
    AppRoutingModule,
    FormsModule, ReactiveFormsModule.withConfig({warnOnNgModelWithFormControl: 'never'}), MatRadioModule
  ],
  providers: [ CookieService ,Uspass],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
